server:
  port: 8080
spring:
  mvc:
    favicon:
      enabled: false
  profiles:
    active: dev
  http:
    converters:
      preferred-json-mapper: gson
  servlet:
    multipart:
      max-file-size: 10MB
  # 配置缓存,初始缓存容量,最大容量,过期时间
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=1000,expireAfterAccess=1h
  datasource:
    separator: $$
    # hikari配置
    hikari:
      auto-commit: true
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      minimum-idle: 5
      maximum-pool-size: 20
  mail:
    host: smtp.iszhiqiang.cn
    username: test@iszhiqiang.cn
    password: Zh123456
    default-encoding: UTF-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  # flyway配置
  flyway:
    # 启用或禁用 flyway
    enabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    #是否允许不按顺序迁移
    out-of-order: false
    # 执行迁移时是否自动调用验证
    validate-on-migrate: true
    # 迁移脚本的文件分隔名 默认__
    sql-migration-separator: __
    # 当迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false.
    baseline-on-migrate: true
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.iszhouhua.blog.model
  type-enums-package: com.iszhouhua.blog.model.enums
  global-config:
    # 数据库相关配置
    db-config:
      # 数据库表前缀
      table-prefix: blog_
      #主键类型
      id-type: auto
      #数据库类型
      db-type: mysql
    banner: false
oauth:
  gitee:
    client-id: bc0b8e96eeaadc8a9d4f59bb305314ce55eb3a27a48013ed30a07d054c688e32
    client-secret: 5791ec70b56c62d3e9e03b92f94c6fa23e2896912677371a7ff1ec0236570af6
    redirect-uri: https://iszhiqiang.cn/oauth/callback/gitee
    scopes: user_info,emails
  github:
    client-id: 10e9e5b8619c9d2b32cc
    client-secret: 30e3c3438977704ffd8e417f7dff709c5df954c9
    redirect-uri: https://iszhiqiang.cn//oauth/callback/github
    scopes: user